services:
  jingwei-dm-redis:
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/redis:alpine3.20"
    container_name: jingwei-dm-redis
    restart: unless-stopped
    ports:
      - '36379:6379'
    networks:
      - anbao
    volumes:
      - /home/etl/iData/anbao-dm/redis:/data
      - /etc/localtime:/etc/localtime
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  jingwei-dm8:
    image: "dm8_single:dm8_20240715_rev232765_x86_rh6_64"
    container_name: jingwei-dm8
    restart: unless-stopped
    ports:
      - '35236:5236'
    networks:
      - anbao
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/anbao/db/dm:/opt/dmdbms/data
      - /opt/anbao/running/healthcheck.sh:/opt/dmdbms/bin/healthcheck.sh
    environment:
      PAGE_SIZE: 16
      LD_LIBRARY_PATH: /opt/dmdbms/bin
      EXTENT_SIZE: 32
      BLANK_PAD_MODE: 1
      LOG_SIZE: 1024
      UNICODE_FLAG: 1
      LENGTH_IN_CHAR: 1
      INSTANCE_NAME: anbao_dm8
    healthcheck:
      test: ['CMD', '/opt/dmdbms/bin/healthcheck.sh']
      interval: 10s
      timeout: 5s
      retries: 5
  jingwei-backend:
    image: "docker.io/library/jingwei-admin:latest"
    container_name: jingwei-backend
    privileged: true
    entrypoint: java -Dspring.config.location=/opt/anbao/project/config/application.yml,/opt/anbao/project/config/application-dev.yml -Dserver.port=8080 -jar jingwei-admin.jar
    restart: unless-stopped 
    environment:
      UPLOAD_JINGWEI_PATH: /opt/anbao/project/common
    depends_on:
      - jingwei-dm8
      - jingwei-dm-redis
    ports:
      - "38089:8080"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/opt/anbao/project/common:/opt/anbao/project/common"
      - "/opt/anbao/project/config:/opt/anbao/project/config"
      - "/opt/anbao/map:/opt/anbao/map"
      - "/opt/anbao/project/GISKey.lic:/jingwei/server/GISKey.lic"
      - "/opt/anbao/project/jingwei-admin.jar:/jingwei-admin.jar"
      - "/:/opt/anbao/map/root"
      - "/opt/anbao/map/root/media:/usb"
    networks:
      - anbao
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1500M
  jingwei-frontend:
    #image: nginx:1.22.1
    #image: openresty/openresty:noble-amd64
    image: registry.cn-beijing.aliyuncs.com/dc_huzy/openresty:noble-amd64
    container_name: jingwei-frontend
    privileged: true
    restart: unless-stopped 
    depends_on:
      - jingwei-backend
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "38083:80"
      - "38443:443"
    networks:
      - anbao
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/anbao/map:/opt/anbao/map
      - /opt/anbao/running/bind.ini:/usr/local/openresty/nginx/conf/bind.ini
      #- /opt/anbao/running/nginx.conf:/etc/nginx/nginx.conf
      # 证书映射
      # - /docker/nginx/cert:/etc/nginx/cert
      # 配置文件映射
      # - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 页面目录
      #- /opt/anbao/running/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/anbao/running/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - /opt/anbao/running/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/anbao/running/dist:/usr/local/openresty/nginx/html
      - /opt/anbao/project/web/SCMAP:/opt/anbao/project/web/SCMAP
      - /opt/anbao/project/common:/opt/anbao/project/common
      # 日志目录
      - /opt/anbao/running/log:/var/log/nginx
      - /:/opt/anbao/map/root
      - /opt/anbao/map/root/media:/usb
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  jingweipy:
    image: "jingwei-jingweipy:noble-dev"
    container_name: jingwei-jingweipy
    restart: unless-stopped 
    command: ["/opt/anbao/venv/bin/python", "jingweipy/brun/main.py"]
    depends_on:
      - jingwei-backend
    privileged: true
    environment:
      PATH: "/opt/anbao/venv/bin:$PATH"
      DISPLAY: "$DISPLAY" # ":0"
      QT_QPA_PLATFORM: "offscreen" # "offscreen" "xcb"
      XDG_RUNTIME_DIR: "/tmp/runtime-root"
      JINGWEIPY_PROFILE: "prod"
      PROJECT_VENV_PREFIX: "python3.12"
      JINGWEI_SERVER_HOST: "jingwei-backend"
      JINGWEI_SERVER_PORT: 8080
      MAPPING_EXPORT_NGINX_HOST: "172.31.100.33"
      MAPPING_EXPORT_NGINX_PORT: 38083
      MAP_BASE_URL: "http://172.31.100.33:38083"
      MAP_MAIN_BASE_URL: "http://172.31.100.33:38083"
      WEB_HANDLER_TIMEOUT: 300
      CIRCLE_RADIUS_COEFFICIENT: 1.3
      ENABLE_POINT_CLUSTER: False
      PYTHONPATH: "/usr/lib/python3/dist-packages:/opt/anbao/venv/lib/python3.12/opt/anbao/venv/lib/python3.12/site-packages:$PYTHONPATH"
      LOGGER_LEVEL: "DEBUG:DEBUG"
    ports:
      - "35888:5888"
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/anbao/map/qgz:/opt/anbao/map/qgz
      #- /opt/anbao/running/jingweipy:/opt/anbao/jingweipy
      - /:/opt/anbao/root
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - anbao
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1500M
  jingweiprinter:
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/jingweiprinter:v1.0.14-550"
    container_name: jingwei-jingweiprinter
    restart: unless-stopped 
    depends_on:
      - jingwei-backend
    privileged: true
    environment:
      DISPLAY: "$DISPLAY" # ":0"
      QT_QPA_PLATFORM: "offscreen" # "offscreen" "xcb"
      XDG_RUNTIME_DIR: "/tmp/runtime-root"
      JINGWEI_SERVER_HOST: "jingwei-backend"
      JINGWEI_SERVER_PORT: 8080
      MAPPING_EXPORT_NGINX_HOST: "172.31.100.33"
      MAPPING_EXPORT_NGINX_PORT: 38083
      MAP_BASE_URL: "http://172.31.100.33:38083"
      MAP_MAIN_BASE_URL: "http://172.31.100.33:38083"
      WEB_HANDLER_TIMEOUT: 300
      CIRCLE_RADIUS_COEFFICIENT: 1.3
      ENABLE_POINT_CLUSTER: False
    ports:
      - "35890:5890"
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/anbao/map/qgz:/opt/anbao/map/qgz
      #- /opt/anbao/running/jingweipy:/opt/anbao/jingweipy
      - /:/opt/anbao/root
      #- /dev/dri/card0:/dev/dri/card0
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/anbao/running/config-prod.yaml:/usr/local/bin/conf/config.yaml
    networks:
      - anbao
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1500M
networks:
  anbao:
    external: true
    name: anbao
  default:
    driver: bridge
